# Generated by Django 3.2.9 on 2021-11-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
